name: BuildTestApplication
on:
  push:
    branches:
      - dllexp
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Restore Projects
        run: |
          nuget restore "$Env:GITHUB_WORKSPACE\src"
      - name: Build SDK
        run: |
          cd "$Env:GITHUB_WORKSPACE\src"
          .\DllExport.bat -action Restore
          .\DllExport.bat -hMSBuild /t:Build /p:Configuration=Release /p:Platform=x86
      - name: Tree
        run: |
          tree /F /A $Env:GITHUB_WORKSPACE\src
      - name: Upload　TestApplication
        uses: actions/upload-artifact@v1
        with:
          name: ReleaseExample
          path: ${{github.workspace}}src\TestApplication\bin\x86\Release
          retention-days: 1